version: "3.8"
services:
  web:
    build: ./TranscriptionFront
    ports:
      - 4998:4998
    networks:
      - net
  api:
    build: ./TranscriptionAPI
    ports:
      - 4999:4999
    networks:
      - net

networks:
  net: 
    driver: bridge